export const labWorks = [
    {id: 1, title: 'Создание первого приложения', pdf_id: 1},
    {id: 2, title: 'Работа с элементами', pdf_id: 2},
    {id: 3, title: 'Работа с экранами', pdf_id: 3},
    {id: 4, title: 'Стили и темы', pdf_id: 4},
    {id: 5, title: 'Работа со списками', pdf_id: 5},
    {id: 6, title: 'Работа с анимацией', pdf_id: 6},
    {id: 7, title: 'Работа с картами', pdf_id: 7},
    {id: 8, title: 'Создание виджета', pdf_id: 8},
    {id: 9, title: 'Работа с меню', pdf_id: 9},
    {id: 10, title: 'Работа с диалоговыми окнами', pdf_id: 10},
    {id: 11, title: 'Работа с уведомлениями', pdf_id: 11},
    {id: 12, title: 'Работа с аудио', pdf_id: 12},
    {id: 13, title: 'Работа с видео', pdf_id: 13},
    {id: 14, title: 'Работа с камерой', pdf_id: 14},
    {id: 15, title: 'Работа с настройками и БД', pdf_id: 15},
];