export const pdf = [
    {title: 'Лабораторная работа №1', file_name: 'lab_work_1.pdf'},
    {title: 'Лабораторная работа №2', file_name: 'lab_work_2.pdf'},
    {title: 'Лабораторная работа №3', file_name: 'lab_work_3.pdf'},
    {title: 'Лабораторная работа №4', file_name: 'lab_work_4.pdf'},
    {title: 'Лабораторная работа №5', file_name: 'lab_work_5.pdf'},
    {title: 'Лабораторная работа №6', file_name: 'lab_work_6.pdf'},
    {title: 'Лабораторная работа №7', file_name: 'lab_work_7.pdf'},
    {title: 'Лабораторная работа №8', file_name: 'lab_work_8.pdf'},
    {title: 'Лабораторная работа №9', file_name: 'lab_work_9.pdf'},
    {title: 'Лабораторная работа №10', file_name: 'lab_work_10.pdf'},
    {title: 'Лабораторная работа №11', file_name: 'lab_work_11.pdf'},
    {title: 'Лабораторная работа №12', file_name: 'lab_work_12.pdf'},
    {title: 'Лабораторная работа №13', file_name: 'lab_work_13.pdf'},
    {title: 'Лабораторная работа №14', file_name: 'lab_work_14.pdf'},
    {title: 'Лабораторная работа №15', file_name: 'lab_work_15.pdf'},
];