export const pdf = [
    {title: 'Лабораторная работа №1', file_id: '1wKRIiiRgPHOGmFriDhfk1HDI4o0arrl1'},
    {title: 'Лабораторная работа №2', file_id: '1nXFiLloQj8qLOT5QR8QYRBkEn_3YVzV5'},
    {title: 'Лабораторная работа №3', file_id: '1AUjY1c08ZlE_aqxCpbOBPEmbsyGhmuti'},
    {title: 'Лабораторная работа №4', file_id: '1ffP5asUwSnSfZuUxkdSxWUmFN40cJPjc'},
    {title: 'Лабораторная работа №5', file_id: '1GV3rXIbnbpg5axAoSj4fnH2D5rENwNDr'},
    {title: 'Лабораторная работа №6', file_id: '11Di01K8sVwwwz-UuW4X9m9QRkaajpDkh'},
    {title: 'Лабораторная работа №7', file_id: '1TgUfaMdTQ_H4Q1gjDtp4WqlZkLm-UPHE'},
    {title: 'Лабораторная работа №8', file_id: '1UVwVNNjCRBMdCqtJuZVVmXGqmjQVadu9'},
    {title: 'Лабораторная работа №9', file_id: '132ONTT4WMBVHloH9hm0lwTPrE7sAVWmk'},
    {title: 'Лабораторная работа №10', file_id: '1jmMnVu9Lkg3E9IXu9YyKeBrOhkgecIxU'},
    {title: 'Лабораторная работа №11', file_id: '17wUt5uEIKxODFV5xGZT7zH0xRG83f83e'},
    {title: 'Лабораторная работа №12', file_id: '1UZAehn1qHyNGvBAJeQKDgJONmh1ikQmk'},
    {title: 'Лабораторная работа №13', file_id: '1XwQff2bvVwIVojvvG2v8FXcmJ_In6qtY'},
    {title: 'Лабораторная работа №14', file_id: '1maTmMUFeYjA7V4EItmoHKawe-PMKQSK7'},
    {title: 'Лабораторная работа №15', file_id: '1UyyD7Yeb6nMxCjCCuUVjKp3bjFSXGSJc'},
];